# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlInterp
version:      0.05
version_from: Perl.pm
installdirs:  site
requires:
    Data::Dumper:                  2.101
    Test::More:                    0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
