# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlInterp
version:      0.03
version_from: Perl.pm
installdirs:  site
requires:
    MIME::Base64:                  0.0
    Storable:                      0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
